### ISSUE TITLE
Scoreboard Issue

### ISSUE THREAD

**Issue by ItsSpaceOG** [qIooIp/Notorious#1]
Currently experiencing this issue in my console.

Error - https://hastebin.com/ucedivodey.bash

**Comment by qIooIp** [comment]
Hastebin is currently not working! Please use https://pastebin.com.

**Comment by qIooIp** [comment]
Is this the only error or are they repeating?

**Comment by ItsSpaceOG** [comment]
I believe this is the only error, just no scoreboard shows up, even if I
start a sotw timer or go into staff mode.

**Comment by qIooIp** [comment]
Can you paste whole latest.log to hastebin?

**Comment by qIooIp** [comment]
This should be fixed now. If the error persists please open another Issue.
