### ISSUE TITLE
PVP ENABLE BUG

### ISSUE THREAD

**Issue by oMontey** [qIooIp/Notorious#10]
when i type /pvp enable, this happens https://gyazo.com/63b942a9ea7898a9e8c6b911ea9f46bf

**Comment by qIooIp** [comment]
Would you mind sending me whole latest.log?

**Comment by qIooIp** [comment]
This has been fixed. Update to latest Notorious version and follow instructions in Update Log to setup it properly since some things in config.yml were changed.
