### ISSUE TITLE
Brand new server, doesn't work

### ISSUE THREAD

**Issue by FrostyTheDankman** [qIooIp/Notorious#18]
Host: Beastnode.com
Brand new server
No other plugins
Everything fresh
https://www.youtube.com/watch?v=IJTM2y5Q_Ss&feature=youtu.be

I know I didnt have essentials but i added it right away and it still didn't work

**Comment by qIooIp** [comment]
How about actually adding Notorious to the plugin folder?

**Comment by qIooIp** [comment]
Would you mind sending me whole latest.log?

**Comment by FrostyTheDankman** [comment]
http://www.filedropper.com/latest_1

**Comment by qIooIp** [comment]
New version has been released with permissions support. Read the update log on spigot page since rank detection system was replaced with permissions and you will have to change some things.
