### ISSUE TITLE
[Scoreboard broken],[Console spam]

### ISSUE THREAD

**Issue by Herblerp** [qIooIp/Notorious#19]
The scoreboard does not work and the console is being spammed. Im also not sure what permissions plugin to use, and what server version to use. What server version and plugins are you running?

[latest.txt](https://github.com/qIooIp/Notorious/files/1278608/latest.txt)

**Comment by Herblerp** [comment]
Fixed it, apparently a faulty (or missing) permissions plugin causes notorious to go completely mad. Im using spigot 1.8.8 with the latest luckyperms version. You should add to your "addition information" section what spigot version(s) to use and what permissions plugins you can use. Also that you have to install a permissions plugin or the plugin doesn't work properly.

**Comment by qIooIp** [comment]
Glad to hear you fixed it.
