### ISSUE TITLE
Kit issues

### ISSUE THREAD

**Issue by Shun1030** [qIooIp/Notorious#2]
This issus occurs when using the kit

All Log - https://hastebin.com/uwenibiyol.md

**Comment by qIooIp** [comment]
Hastebin is currently not working! Please use https://pastebin.com.

**Comment by Shun1030** [comment]
OK

Archer Log - https://pastebin.com/65d4c9CM
Rogue Log - https://pastebin.com/8WPm3VNY
Bard Log - https://pastebin.com/wRJbMmAG

**Comment by qIooIp** [comment]
Issue is fixed. Download latest version from https://www.spigotmc.org/resources/hcf-notorious-core.29511/history

**Comment by Shun1030** [comment]
Thank you!!
