### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by DroppedInTheSky** [qIooIp/Notorious#4]
This happens when players connect: https://pastebin.com/hJQjdqF2

While on the server: https://pastebin.com/LW6VKLeK

And when they disconnect: https://pastebin.com/bKHqtdH4

idk why this happens, any help?

**Comment by qIooIp** [comment]
What permissions plugin are you using?

**Comment by DroppedInTheSky** [comment]
Im using zPermissions

**Comment by qIooIp** [comment]
Thank you for enlightening me. I will change it to permissions system in next couple of days.

**Comment by DroppedInTheSky** [comment]
Lol... Perfect, thank you very much :D

**Comment by qIooIp** [comment]
Latest Notorious version now supports permissions. Follow instructions in Update Log to change what is needed and to setup it properly.
