### ISSUE TITLE
Kit Problem

### ISSUE THREAD

**Issue by oMontey** [qIooIp/Notorious#7]
Hey there, so i made a kit using /kit create NORMAL OP 5 just to test and see if it works.. When i typed /kit give <my ign> OP, it said i received my kit, but i didn't.. This is the error in console!
-
-
25.08 08:56:28 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
25.08 08:56:28 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
25.08 08:56:28 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
25.08 08:56:28 [Server] INFO at java.lang.Thread.run(Thread.java:745)
25.08 08:56:28 [Server] INFO Caused by: java.lang.NullPointerException
25.08 08:56:28 [Server] INFO at me.qiooip.notorious.scoreboard.ScoreboardHandler$1.run(ScoreboardHandler.java:143)
25.08 08:56:28 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
25.08 08:56:28 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
25.08 08:56:28 [Server] INFO ... 3 more
25.08 08:56:28 [Server] WARN Exception in thread "Craft Scheduler Thread - 1208" 
25.08 08:56:28 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Notorious v2.0.8 generated an exception while executing task 23
25.08 08:56:28 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
25.08 08:56:28 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
25.08 08:56:28 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
25.08 08:56:28 [Server] INFO at java.lang.Thread.run(Thread.java:745)
25.08 08:56:28 [Server] INFO Caused by: java.lang.NullPointerException
25.08 08:56:28 [Server] INFO at me.qiooip.notorious.scoreboard.ScoreboardHandler$1.run(ScoreboardHandler.java:143)
25.08 08:56:28 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
25.08 08:56:28 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
25.08 08:56:28 [Server] INFO ... 3 more
25.08 08:56:28 [Server] WARN Exception in thread "Craft Scheduler Thread - 1209" 
25.08 08:56:28 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Notorious v2.0.8 generated an exception while executing task 23
25.08 08:56:28 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
25.08 08:56:28 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
25.08 08:56:28 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
25.08 08:56:28 [Server] INFO at java.lang.Thread.run(Thread.java:745)
25.08 08:56:28 [Server] INFO Caused by: java.lang.NullPointerException
25.08 08:56:28 [Server] INFO at me.qiooip.notorious.scoreboard.ScoreboardHandler$1.run(ScoreboardHandler.java:143)
25.08 08:56:28 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
25.08 08:56:28 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
25.08 08:56:28 [Server] INFO ... 3 more
25.08 08:56:28 [Server] WARN Exception in thread "Craft Scheduler Thread - 1210" 
25.08 08:56:28 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Notorious v2.0.8 generated an exception while executing task 23
25.08 08:56:28 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
25.08 08:56:28 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
25.08 08:56:28 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
25.08 08:56:28 [Server] INFO at java.lang.Thread.run(Thread.java:745)
25.08 08:56:28 [Server] INFO Caused by: java.lang.NullPointerException
25.08 08:56:28 [Server] INFO at me.qiooip.notorious.scoreboard.ScoreboardHandler$1.run(ScoreboardHandler.java:143)
25.08 08:56:28 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
25.08 08:56:28 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
25.08 08:56:28 [Server] INFO ... 3 more
25.08 08:56:29 [Server] WARN Exception in thread "Craft Scheduler Thread - 1211" 
25.08 08:56:29 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Notorious v2.0.8 generated an exception while executing task 23
25.08 08:56:29 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
25.08 08:56:29 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
25.08 08:56:29 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
25.08 08:56:29 [Server] INFO at java.lang.Thread.run(Thread.java:745)
25.08 08:56:29 [Server] INFO Caused by: java.lang.NullPointerException
25.08 08:56:29 [Server] INFO at me.qiooip.notorious.scoreboard.ScoreboardHandler$1.run(ScoreboardHandler.java:143)
25.08 08:56:29 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
25.08 08:56:29 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
25.08 08:56:29 [Server] INFO ... 3 more
25.08 08:56:29 [Server] WARN Exception in thread "Craft Scheduler Thread - 1212" 
25.08 08:56:29 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Notorious v2.0.8 generated an exception while executing task 23
25.08 08:56:29 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
25.08 08:56:29 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
25.08 08:56:29 [Multicraft] Skipped 20 lines due to rate limit (100/s)
25.08 08:56:29 [Server] WARN Exception in thread "Craft Scheduler Thread - 1214" 
25.08 08:56:29 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Notorious v2.0.8 generated an exception while executing task 23
25.08 08:56:29 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
25.08 08:56:29 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
25.08 08:56:29 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
25.08 08:56:29 [Server] INFO at java.lang.Thread.run(Thread.java:745)
25.08 08:56:29 [Server] INFO Caused by: java.lang.NullPointerException
25.08 08:56:29 [Server] INFO at me.qiooip.notorious.scoreboard.ScoreboardHandler$1.run(ScoreboardHandler.java:143)
25.08 08:56:29 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
25.08 08:56:29 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
25.08 08:56:29 [Server] INFO ... 3 more
25.08 08:56:29 [Server] WARN Exception in thread "Craft Scheduler Thread - 1191" 
25.08 08:56:29 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Notorious v2.0.8 generated an exception while executing task 23
25.08 08:56:29 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
25.08 08:56:29 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
25.08 08:56:29 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
25.08 08:56:29 [Server] INFO at java.lang.Thread.run(Thread.java:745)
25.08 08:56:29 [Server] INFO Caused by: java.lang.NullPointerException
25.08 08:56:29 [Server] INFO at me.qiooip.notorious.scoreboard.ScoreboardHandler$1.run(ScoreboardHandler.java:143)
25.08 08:56:29 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
25.08 08:56:29 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
25.08 08:56:29 [Server] INFO ... 3 more
25.08 08:56:29 [Server] WARN Exception in thread "Craft Scheduler Thread - 1216" 
25.08 08:56:29 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Notorious v2.0.8 generated an exception while executing task 23
25.08 08:56:29 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
25.08 08:56:29 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
25.08 08:56:29 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
25.08 08:56:29 [Server] INFO at java.lang.Thread.run(Thread.java:745)
25.08 08:56:29 [Server] INFO Caused by: java.lang.NullPointerException
25.08 08:56:29 [Server] INFO at me.qiooip.notorious.scoreboard.ScoreboardHandler$1.run(ScoreboardHandler.java:143)
25.08 08:56:29 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
25.08 08:56:29 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
25.08 08:56:29 [Server] INFO ... 3 more

**Comment by ItsNature** [comment]
This error has nothing to do with kits.

**Comment by qIooIp** [comment]
This is playerdata problem that has been fixed earlier. Stop your server, go to your playerdata directory and delete every playerdata file that has 0 bytes (that is empty).
