### ISSUE TITLE
2 END BUGS! I NEED YOU TO RESPOND / FIX THIS ISSUE FAST!!

### ISSUE THREAD

**Issue by oMontey** [qIooIp/Notorious#8]
Hey there, so i am working on my server and noticed that i cant make an end portal in end? i need it for end exit... is this a bug or what? ive attached a video showing u about the bug.. here it is: https://youtu.be/95z9z9ukZDE
And also.. when i / players go through an end portal, it puts me / players on obsidian when i set end spawn already? again, this is all in the video... please help me! i dont wanna delay my sotw, sotw is in 1 week from now (09/02/17) so i am limited on time.. please reply quickly
Notorious version im using: 2.0.8

**Comment by qIooIp** [comment]
You have to use /portal command to create End and Nether exits.
